#!/bin/bash
echo "=== 测试温度详情页面 ==="
echo ""
echo "1. 测试API是否正常:"
curl -s "http://localhost:3001/api/multi-index-temperature?startDate=20210106&endDate=20260106" | jq '{success: .success, composite: (.data.composite.distribution != null), indices: (.data.indices | keys)}'
echo ""
echo "2. 测试页面是否可访问:"
curl -s -o /dev/null -w "HTTP状态码: %{http_code}\n" "http://localhost:3001/temperature-detail.html"
echo ""
echo "3. 测试JavaScript文件是否可访问:"
curl -s -o /dev/null -w "HTTP状态码: %{http_code}\n" "http://localhost:3001/temperature-detail.js"
echo ""
echo "=== 测试完成 ==="
echo ""
echo "请在浏览器中打开以下链接并查看控制台输出:"
echo "http://localhost:3001/temperature-detail.html"
echo ""
echo "或使用浏览器预览:"
echo "http://127.0.0.1:57589/temperature-detail.html"
